project_id = "firhmtfjxagrmyltsypd"

[functions.parse-students-pdf]
verify_jwt = false

[functions.parse-grades-pdf]
verify_jwt = false

[functions.parse-classes-pdf]
verify_jwt = false

[functions.parse-teachers-pdf]
verify_jwt = false

[functions.parse-subjects-pdf]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false

[functions.event-share]
verify_jwt = false

[functions.push-public-key]
verify_jwt = false

[functions.join-branding]
verify_jwt = false
