project_id = "firhmtfjxagrmyltsypd"

[functions.parse-students-pdf]
verify_jwt = false

[functions.parse-classes-pdf]
verify_jwt = false

[functions.parse-teachers-pdf]
verify_jwt = false

[functions.parse-subjects-pdf]
verify_jwt = false

[functions.generate-timetable]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.notify-new-user]
verify_jwt = false

[functions.conflict-chat]
verify_jwt = false
